Fr 31
TherapistTrack/therapistTrackApp pull request #7
Opened 2024-05-09 03:02 UTC by xtsebas

Realice la coleccion de files y consultas en la db :)

2024-05-10 03:44 UTC, DanielRasho requested changes
Se requiren varios cambios:

- Corrección de definicion de campos en `design.js`
- Creación de coleccion `FileTemplate`
- Cambiar BSon type de `Record` para la validación de schema.

2024-05-10 03:44 UTC, DanielRasho commented on Database/design.js
> +  },
Metadata, debería ser un array de objetos NO un objeto. 
Donde los objetos que contiene este array sigan   la estructura de` name, value, type, required description`

2024-05-10 03:44 UTC, DanielRasho commented on Database/design.js
> +
Falta crear la colección de `FileTemplate` para se definan los campos de metadata que debe tener un archivo. 
Todo File template se le debe asignar a una doctora.

2024-05-10 03:44 UTC, DanielRasho commented on Database/design.js
> +  category: '',
En algún lugar se debe guardar las categorías que existen para un archivo. 
Estas categorías tambien son definidas por una doctora, en la colección fileTemplate.

2024-05-10 03:44 UTC, DanielRasho commented on Database/scripts/06-record.js
> +            patient: {
Esto debe ser tipo ObjectID

2024-05-10 03:44 UTC, DanielRasho commented on Database/scripts/06-record.js
> +                bsonType: "string",
Debe ser tipo ObjectID

2024-05-12 00:55 UTC, xtsebas commented
se arreglo y agrego filetemplate, hay un problema en el bsonType pero esta igual en todo

2024-05-12 21:03 UTC, DanielRasho approved these changes
Nice!

2024-05-12 21:04 UTC, merged